<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="2" tests="0"
           time="0.014">
    <testcase classname="sample.test_sample" file="sample/test_sample.py"
              line="2"
              name="test_sample_xfail_with_super_long_name_for_test_purposes_we_would_not_want_it_to_spill_out_of_the_box_init"
              time="0.000557899475098">
        <skipped message="expected test failure"></skipped>
    </testcase>
    <testcase classname="sample.test_sample" file="sample/test_sample.py"
              line="6" name="test_sample_xpass" time="0.000342845916748">
        <skipped message="xfail-marked test passes unexpectedly">None</skipped>
    </testcase>
</testsuite>